newsfeed/urls.py
from django.urls import path
from newsfeed.views import (HomePageView, NewsFeedListing, ChangeVoteCount)

app_name = "news"

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('news', NewsFeedListing.as_view(), name='news-list'),
    path('change_vote_count', ChangeVoteCount.as_view(), name='change-vote-count'),
]

newsfilter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsfeed.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newsfeed/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class TimestampModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        abstract = True


class Category(TimestampModel):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return str(self.name)


class User(AbstractUser, TimestampModel):
    preferences = models.ManyToManyField(
        Category, blank=True, null=True, related_name="user_preference")

    def __str__(self):
        return str(self.username)


class NewsSource(TimestampModel):
    url = models.URLField()
    headers = models.JSONField(null=True, blank=True)
    params = models.JSONField(null=True, blank=True)

    def __str__(self):
        return str(self.url)


class NewsData(TimestampModel):
    url = models.URLField(unique=True)
    title = models.TextField()
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    positive_votes = models.BigIntegerField(default=0)
    negative_votes = models.BigIntegerField(default=0)

    def __str__(self):
        return str(self.url)

newsfeed/views.py
import json
import logging
from django.views.generic import TemplateView, ListView
from django.views import View
from django.http import JsonResponse
from newsfeed.models import NewsData
from http import HTTPStatus

logger = logging.getLogger("newsfilter")


class HomePageView(TemplateView):
    template_name = 'newsfeed/base.html'


class NewsFeedListing(ListView):
    template_name = "newsfeed/news_list.html"
    model = NewsData
    paginate_by = 10
    context_object_name = 'news_list'
    ordering = '-positive_votes'


class ChangeVoteCount(View):

    def put(self, request):
        try:
            data = json.loads(request.body)
            vote_type = str(data.get('voteType'))
            news_id = data.get('newsId')
            if vote_type and news_id:
                news_obj = NewsData.objects.filter(pk=news_id).first()
                if int(vote_type) == 0:
                    news_obj.negative_votes += 1
                elif int(vote_type) == 1:
                    news_obj.positive_votes += 1
                news_obj.save()
                resp = {'success': 'vote done.'}
                logger.info(
                    dict(
                        message="Vote done",
                        class_name="ChangeVoteCount",
                        method_name="post",
                    )
                )
            return JsonResponse(resp, status=HTTPStatus.OK)
        except Exception as e:
            logger.error(
                dict(
                    message="'Exception in change vote'",
                    class_name="ChangeVoteCount",
                    method_name="post",
                    errors=e,
                )
            )
            return JsonResponse({"message": "failed"}, status=HTTPStatus.INTERNAL_SERVER_ERROR)

templates/newsfeed/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'news:news-list' %}">NewsFeed</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'news:news-list' %}">Home</a></li>
      <!-- <li><a href="#">Page 1</a></li> -->
    </ul>
  </div>
</nav>
  
<div class="container">
  <h3>Latest News</h3>

  {% block container %}
  {% endblock %}

</div>
{% block javascript %}
{% endblock %}
</body>
</html>

templates/newsfeed/email_template.html
<html>
    <head></head>
    <body>
        <h1>Hi, {{username}}</h1>
        <div class="row">
            <p>
                As per your preference in {{category}}, we found relavant news for you.
            </p>
        </div>
        <div class="row">
            <a href="{{url}}" >Click here.</a>
        </div>
    </body>
</html>

templates/newsfeed/news_list.html
{% extends 'newsfeed/base.html' %}
{% load static %}

{% block container %}
{% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 offset-lg-2">
            <div class="infinite-container">
                {% for news in news_list %}
                <div class="infinite-item">
                    <div class="col-sm-12">

                        <h3>
                            <a href="{{news.url}}" target="_blank" style="color: black;">{{news.title}}</a>
                        </h3>
                        <div class="col-sm-9">
                            <p>{{news.content}}</p>
                            <a href="{{news.url}}" target="_blank">Read more</a>
                        </div>
                        <div class="col-sm-3">
                            <button class="btn btn-primary" onclick="changeVoteCount(1, {{news.id}}, '{% url 'news:change-vote-count' %}')">Vote up</button>
                            <button class="btn btn-warning" style="color:black"
                                onclick="changeVoteCount(0, {{news.id}}, '{% url 'news:change-vote-count' %}')">Vote down</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="col-sm-6" style="margin-top: 20px;margin-bottom: 20px;">
                    {% if page_obj.has_previous %}
                    <a class="infinite-more-link btn btn-primary"
                        href="?page={{ page_obj.previous_page_number }}">Previous page</a>
                    {% endif %}

                    {% if page_obj.has_next %}
                    <a class="infinite-more-link btn btn-primary" href="?page={{ page_obj.next_page_number }}">More</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}
<!-- <script type="text/javascript">
    let csrftoken = $("[name=csrfmiddlewaretoken]").val();

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    });

    $(document).ready(function () {
        // var infinite = new Waypoint.Infinite({
        //     element: $('.infinite-container')[0],
        //     offset: function() {
        //         return -this.element.clientHeight
        //     }
        // });

    });
    function changeVoteCount(votyType, newsId) {
        $.ajax({
            url: "{% url 'news:change-vote-count' %}",
            type: "PUT",
            contentType: 'application/json',
            data: JSON.stringify({
                'voteType': votyType,
                'newsId': newsId,
            }),
            dataType: 'json',
            success: function (data) {
                alert("Thanks for Vote")
            }
        });
    }
</script> -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script src="{% static 'js/changeVote.js' %}"></script>
{% endblock %}